package KargoEntityBean;

import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hilmi
 */
public class PersonelSayfası extends javax.swing.JFrame {

    /**
     * Creates new form PersonelSayfası
     */
    DefaultTableModel dtm = new DefaultTableModel();
    DefaultTableModel dtm1 = new DefaultTableModel();

    public PersonelSayfası() {

        initComponents();
        ResetDtm();

        dtm1.setColumnIdentifiers(new String[]{"TC", "AD", "SOYAD", "TEL", "ADRES"});
        jTable2.setModel(dtm1);
        this.getContentPane().setBackground(Color.WHITE);

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("KargoVeriTaban_PU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("SELECT K FROM Kargolar K");
        List<Kargolar> kargo = q.getResultList();
        for (Kargolar kargo1 : kargo) {
            dtm.addRow(new Object[]{kargo1.getKargoid(), kargo1.getAlantc(), kargo1.getGönderentc()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txttc = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(990, 470));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(880, 500));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Kargo Merkezinde ");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Yola Çıktı");
        jRadioButton2.setContentAreaFilled(false);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Gümrükte");
        jRadioButton3.setToolTipText("");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Müşteriye Teslim Edildi");

        jButton1.setText("Kaydet  ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 390, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 654, 160));

        jButton3.setText("Tümünü Gör");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 102, -1));

        jButton6.setText("İptal");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 100, -1));

        jTabbedPane1.addTab("Hareket Ekle", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 540, 220));

        jButton2.setText("Tümünü Listele");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 119, -1));

        jButton4.setText("Dosyaya Listele");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 70, 120, -1));

        jLabel1.setText("TC'ye göre ara:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));
        jPanel2.add(txttc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 110, -1));

        jButton5.setText("Ara");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        jTabbedPane1.addTab("Müşteri Bilgileri", jPanel2);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 750, 430);

        setSize(new java.awt.Dimension(758, 460));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("KargoVeriTaban_PU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("SELECT a FROM Alankisi a ");
        List<Alankisi> alankisiList = q.getResultList();
        for (Alankisi alankisiList1 : alankisiList) {
            dtm1.addRow(new Object[]{alankisiList1.getTc(), alankisiList1.getAd(), alankisiList1.getSoyad(), alankisiList1.getAdres(), alankisiList1.getTel()});
        }

        Query q1 = em.createQuery("SELECT g FROM Gonderenkisi g");
        List<Gonderenkisi> gonderenkisiList = q1.getResultList();
        for (Gonderenkisi gonderenkisiList1 : gonderenkisiList) {
            dtm1.addRow(new Object[]{gonderenkisiList1.getTc(), gonderenkisiList1.getAd(), gonderenkisiList1.getSoyad(),
                gonderenkisiList1.getAdres(), gonderenkisiList1.getTel()});
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ResetDtm();
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("KargoVeriTaban_PU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("SELECT K FROM Kargolar K");
        List<Kargolar> kargo = q.getResultList();
        for (Kargolar kargo1 : kargo) {
            dtm.addRow(new Object[]{kargo1.getKargoid(), kargo1.getAlantc(), kargo1.getGönderentc()});
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int id = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("KargoVeriTaban_PU");
        EntityManager em = emf.createEntityManager();
        Takip2 t = new Takip2();
        if (jRadioButton1.isSelected()) {

            try {
                t.setKargoId(id);
                t.setDurum("Merkezde.");

                SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
                String date = dateChooserCombo1.getText();
                java.sql.Date mydate = new java.sql.Date(sdf.parse(date).getTime());

                t.setTarih(mydate);
            } catch (ParseException ex) {
                Logger.getLogger(PersonelSayfası.class.getName()).log(Level.SEVERE, null, ex);
            }

          
        } else if (jRadioButton2.isSelected()) {

            try {
                t.setKargoId(id);
                t.setDurum("Yola çıktı.");
                SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
                String date = dateChooserCombo1.getText();
                java.sql.Date mydate = new java.sql.Date(sdf.parse(date).getTime());
                t.setTarih(mydate);
            } catch (ParseException ex) {
                Logger.getLogger(PersonelSayfası.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (jRadioButton3.isSelected()) {

            try {
                t.setKargoId(id);
                t.setDurum("Gümrükte.");
                SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
                String date = dateChooserCombo1.getText();
                java.sql.Date mydate = new java.sql.Date(sdf.parse(date).getTime());
                t.setTarih(mydate);
            } catch (ParseException ex) {
                Logger.getLogger(PersonelSayfası.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (jRadioButton4.isSelected()) {

            try {
                t.setKargoId(id);
                t.setDurum("Müşteriye ulaştı.");
                SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
                String date = dateChooserCombo1.getText();
                java.sql.Date mydate = new java.sql.Date(sdf.parse(date).getTime());
                t.setTarih(mydate);
            } catch (ParseException ex) {
                Logger.getLogger(PersonelSayfası.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        em.getTransaction().begin();
        em.persist(t);
        em.getTransaction().commit();
        ResetDtm();
        
        
        Query q = em.createQuery("SELECT k FROM Kargolar k WHERE k.kargoid=:Kargo_Id ");
        Query q1 = em.createQuery("SELECT t From Takip2 t WHERE t.kargoId=:KargoId");
        q.setParameter("Kargo_Id", id);
        q1.setParameter("KargoId", id);
        List<Kargolar> kargo = q.getResultList();
        List<Takip2> takip = q1.getResultList();
        for (Kargolar kargo1 : kargo) {
            for (Takip2 takip1 : takip) {
                dtm.setRowCount(0);
                dtm.addRow(new Object[]{kargo1.getKargoid(), kargo1.getAlantc(),
                    kargo1.getGönderentc(), takip1.getDurum(), takip1.getTarih()});
                }
        }

       
       
        em.close();
        emf.close();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        File entityFile= new File ("Kisiler.txt");
        if (!entityFile.exists()) {
            try {
                entityFile.createNewFile();
                FileWriter fw= new FileWriter(entityFile.getAbsoluteFile());
                BufferedWriter bw= new BufferedWriter(fw);
                
                for (int i = 0; i < jTable2.getRowCount(); i++) {
                    for (int j = 0; j < jTable2.getColumnCount(); j++) {
                        bw.write(jTable2.getModel().getValueAt(i, j)+" ");
                    }
                    bw.write("\n");
                    bw.newLine();;
                }
                bw.close();
                fw.close();
                
            } catch (IOException ex) {
                Logger.getLogger(PersonelSayfası.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        JOptionPane.showMessageDialog(this, "Listelendi.");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        dtm1.setRowCount(0);
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("KargoVeriTaban_PU");
        EntityManager em = emf.createEntityManager();
        
        Query q= em.createQuery("SELECT a FROM Alankisi a WHERE a.tc=:atc");
        q.setParameter("atc", txttc.getText()  );
        List <Alankisi> alankisiList = q.getResultList();
        for (Alankisi alankisiList1 : alankisiList) {
            dtm1.addRow(new Object []{alankisiList1.getTc(), alankisiList1.getAd(), alankisiList1.getSoyad(), alankisiList1.getAdres(), alankisiList1.getTel()});
        }
      Query q1= em.createQuery("SELECT g FROM Gonderenkisi g WHERE g.tc=:gtc");
      q1.setParameter("gtc", txttc.getText());
      List <Gonderenkisi> gonderenList=q1.getResultList();
        for (Gonderenkisi gonderenList1 : gonderenList) {
            dtm1.addRow(new Object [] { gonderenList1.getTc(),gonderenList1.getAd(),gonderenList1.getSoyad(),gonderenList1.getAdres(),gonderenList1.getTel()});
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        EntityManagerFactory emf= Persistence.createEntityManagerFactory("KargoVeriTaban_PU");
        EntityManager em= emf.createEntityManager();
        Query q= em.createQuery("DELETE FROM Kargolar k WHERE k.kargoid=:kId");
        q.setParameter("kId", Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString()));
        em.getTransaction().begin();
        q.executeUpdate();
        em.getTransaction().commit();
        em.close();
        emf.close();
        dtm.removeRow(jTable1.getSelectedRow());
    }//GEN-LAST:event_jButton6ActionPerformed


void ResetDtm() {
        dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new String[]{"KARGO ID", "ALICI TC", "GÖNDEREN TC", "HAREKET", "HAREKET TARİHİ"});
        jTable1.setModel(dtm);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonelSayfası.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonelSayfası.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonelSayfası.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonelSayfası.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonelSayfası().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txttc;
    // End of variables declaration//GEN-END:variables
}
