
import java.awt.Color;
import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hilmi
 */
public class PersonelGirisi extends javax.swing.JFrame {

    /**
     * Creates new form PersonelGirisi
     */
    public PersonelGirisi() {
        initComponents();
        
       super.getContentPane().setBackground(Color.PINK);
       
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGirisY = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jsifre = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGirisY.setText("Giriş Yap");
        btnGirisY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGirisYActionPerformed(evt);
            }
        });
        getContentPane().add(btnGirisY, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 86, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Şifre            :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jsifre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsifreActionPerformed(evt);
            }
        });
        getContentPane().add(jsifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 162, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tırtıl.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGirisYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGirisYActionPerformed
        String sifre= "1";
        
        if (String.valueOf(jsifre.getPassword()).equals(sifre)) {
            JOptionPane.showMessageDialog(this,"Giriş başarılı.");
            PersonelSayfası ps= new PersonelSayfası();
            ps.setVisible(true);
            
        }
        else    
        JOptionPane.showMessageDialog(this, "Şifre hatalı.Tekrar deneyin.");
    }//GEN-LAST:event_btnGirisYActionPerformed

    private void jsifreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsifreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jsifreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonelGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonelGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonelGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonelGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonelGirisi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGirisY;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jsifre;
    // End of variables declaration//GEN-END:variables
}
