
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.util.logging.Level;
import java.util.logging.Logger;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hilmi
 */
public class SorgulamaId extends javax.swing.JFrame {

    /**
     * Creates new form Sorgulama
     */
    public SorgulamaId() {
        initComponents();
        super.getContentPane().setBackground(Color.PINK);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        btnsorgula = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtyer = new javax.swing.JTextField();
        txttarıh = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sorgulama");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Kargo Id:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 31));
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 95, -1));

        btnsorgula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnsorgula.setText("Sorgula");
        btnsorgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsorgulaActionPerformed(evt);
            }
        });
        getContentPane().add(btnsorgula, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, 37));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Bulunduğu Yer: ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 110, -1));

        txtyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtyerActionPerformed(evt);
            }
        });
        getContentPane().add(txtyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 220, 30));
        getContentPane().add(txttarıh, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 220, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Girildiği Tarih:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 100, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ucak.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 300));

        setSize(new java.awt.Dimension(505, 330));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsorgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsorgulaActionPerformed
        
            try {
                Connection con= DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app");
                String sql= "SELECT * FROM TAKIP2 WHERE KARGO_ID =?"     ;
                PreparedStatement ps= con.prepareStatement(sql);
                ps.setInt(1, Integer.parseInt(txtid.getText()));
                
                ResultSet rs=ps.executeQuery();
                while(rs.next()) {
                    String KARGO_ID=rs.getString("kargo_ıd");
                    String durum= rs.getString("durum");
                    String tarıh = rs.getString("tarıh");
                    txtid.setText(KARGO_ID);
                    txtyer.setText(durum);
                    txttarıh.setText(tarıh);
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(SorgulamaId.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        

    }//GEN-LAST:event_btnsorgulaActionPerformed

    private void txtyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtyerActionPerformed
       

    }//GEN-LAST:event_txtyerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SorgulamaId.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SorgulamaId.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SorgulamaId.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SorgulamaId.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SorgulamaId().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsorgula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txttarıh;
    private javax.swing.JTextField txtyer;
    // End of variables declaration//GEN-END:variables

}
